### ISSUE TITLE
bundler: failed to load command: tootctl (/var/snap/mastodon-server/31/mastodon/bin/tootctl)

### ISSUE THREAD

**Issue by eeegadds** [dhelonious/mastodon-snap#7] opened 2024-07-07 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

sudo mastodon-server.tootctl accounts create administrator --email xxxxxxxxx --role Owner --confirmed 

get this error  

bundler: failed to load command: tootctl (/var/snap/mastodon-server/31/mastodon/bin/tootctl)
/var/snap/mastodon-server/31/mastodon/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.8.4/lib/action_dispatch/http/content_security_policy.rb:304:in `block in apply_mappings': Invalid content security policy source: nil (ArgumentError)

            raise ArgumentError, "Invalid content security policy source: #{source.inspect}"
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Version

newest

### Architecture

amd64

### OS

Ubuntu 24.04

**Comment by dhelonious** [comment] 2024-07-07 18:20
I cannot reproduce this error. Could you please tell me what commands you used before this one?

By the way, names like "administrator" and "admin" are reserved and cannot be used. But tootctl would tell you if it was working properly.

**Comment by dhelonious** [comment] 2024-08-11 14:30
I will close this for now. If this error occurs again, please reopen it.

**Closed by dhelonious** 2024-08-11 14:30 UTC
Labels: bug, not reproducible
